export const candidates = [
  {
    id: 1,
    name: "Albert Flores",
    timestamp: "23 August, 12:00PM",
    score: 95,
    status: "Shortlisted",
    resume: "Resume.pdf",
  },
  {
    id: 2,
    name: "Wade Warren",
    timestamp: "23 August, 12:00PM",
    score: 88,
    status: "Shortlisted",
    resume: "Resume.pdf",
  },
  {
    id: 3,
    name: "Ronald Richards",
    timestamp: "23 August, 12:00PM",
    score: 92,
    status: "Shortlisted",
    resume: "Resume.pdf",
  },
  {
    id: 4,
    name: "Courtney Henry",
    timestamp: "23 August, 12:00PM",
    score: 79,
    status: "Waitlisted",
    resume: "Resume.pdf",
  },
  {
    id: 5,
    name: "Jerome Bell",
    timestamp: "23 August, 12:00PM",
    score: 86,
    status: "Shortlisted",
    resume: "Resume.pdf",
  },
  {
    id: 6,
    name: "Jacob Jones",
    timestamp: "23 August, 12:00PM",
    score: 72,
    status: "Rejected",
    resume: "Resume.pdf",
  },
  {
    id: 7,
    name: "Albert Flores",
    timestamp: "23 August, 12:00PM",
    score: 91,
    status: "Shortlisted",
    resume: "Resume.pdf",
  },
  {
    id: 8,
    name: "Albert Flores",
    timestamp: "23 August, 12:00PM",
    score: 84,
    status: "Waitlisted",
    resume: "Resume.pdf",
  },
  {
    id: 9,
    name: "Albert Flores",
    timestamp: "23 August, 12:00PM",
    score: 89,
    status: "Shortlisted",
    resume: "Resume.pdf",
  },
  {
    id: 10,
    name: "Albert Flores",
    timestamp: "23 August, 12:00PM",
    score: 76,
    status: "Rejected",
    resume: "Resume.pdf",
  },
];
